name: OGUSDT EMA-21 Alert

on:
  schedule:
    - cron: '*/5 * * * *'   # Tiap 5 menit
  workflow_dispatch:        # Bisa dijalankan manual

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install library
        run: |
          pip install ccxt pandas gtts python-telegram-bot==13.15
          
      - name: Jalankan bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python alert.py
